### ISSUE TITLE
Substrate: Use secure randomness

### ISSUE THREAD

**Issue by cernicc** [eigerco/polka-storage#458]
We are currently using the [insecure randomness ](https://paritytech.github.io/polkadot-sdk/master/pallet_insecure_randomness_collective_flip/index.html) on chain. The reason was faster implementation because if we wanted to use the more secure random algorithm we would also have to switch to BABE consensus algorithm at the time.

This ticket requires you to use the more secure randomness.

Blocked by: 
* #457 

Some more resources:
* https://docs.substrate.io/build/randomness/

**Comment by th7nder** [comment]
Moonbeam is using randomness from the RelayChain -> https://github.com/moonbeam-foundation/moonbeam/blob/6e6bb1cc21343aa7231b6574091d022138c04108/runtime/moonbeam/src/lib.rs#L1301.
And they're using [`pallet-parachain-staking`](https://docs.moonbeam.network/builders/substrate/interfaces/features/staking/), so don't need to use BABE in the parachain.

About [`pallet-drand`](https://github.com/ideal-lab5/idn-sdk/tree/main/pallets/drand), there is a discussion and comparing it to Moonbeam as well: https://kusama.polkassembly.io/post/2645.
