### ISSUE TITLE
general: review project structure

### ISSUE THREAD

**Issue by jmg-duarte** [eigerco/polka-storage#578]
- [x] there are some folders that are most likely no longer needed, namely everything to do with collators.
- [x] `storagext` and `mater` can be merged with their respective clis
- [ ] `primitives` are a bit all over the place, we can probably do better
- [x] `network`, `market-protocols` and `api` can possibly be removed too, or maybe renamed and get some children?

**Comment by cernicc** [comment]
I am reopening this because we still have to review the primitives.

**Comment by cernicc** [comment]
Primitives were done in https://github.com/eigerco/polka-storage/pull/616
