### ISSUE TITLE
Handle multiple concurrent transactions in subxt

### ISSUE THREAD

**Issue by th7nder** [eigerco/polka-storage#641]
We cannot use current subxt client in such a way, that one task sent an extrinsic and waiting for it to be finalized, while the other tries to submit another extrinsic.

This is because Nonce for an account that's included in the transaction is only updated after finalization, and later transaction becomes outdated.

When sending calls from the pipeline/server we'd like to take into the account the transactions that are currently in the pool.

- https://wiki.polkadot.network/docs/build-transaction-construction
- https://github.com/paritytech/subxt/issues/1393#issuecomment-1906308388
- https://github.com/paritytech/json-rpc-interface-spec/issues/156#issuecomment-2111691833

I guess I'm gonna go for getting the nonce from RPC txpool and tracking it manually:
- https://github.com/paritytech/polkadot-staking-miner/blob/0f9aa6143018b7e261658c201f61404bb1a47606/src/commands/monitor.rs#L548
- https://github.com/paritytech/polkadot-staking-miner/blob/0f9aa6143018b7e261658c201f61404bb1a47606/src/commands/monitor.rs#L284

**Comment by jmg-duarte** [comment]
> I guess I'm gonna go for getting the nonce from RPC txpool and tracking it manually:

I'm not sure this is thaaat simple since they transaction may be replaced in the pool. We need to double check that behaviour
