### ISSUE TITLE
Consider additional reward mechanism for Collators

### ISSUE THREAD

**Issue by th7nder** [eigerco/polka-storage#73]
We established in #61 , #62 that we are using economic model of the system parachains based on [Polkadot's RFC-007](https://polkadot-fellows.github.io/RFCs/approved/0007-system-collator-selection.html).

Hence using [collator-selection pallet](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/pallets/collator-selection/src/lib.rs) which implements this mechanism. 

One additional thing to consider is whether we should include a tipping mechanism for Collators by Storage Providers.
Example: 1% of the Storage Provider profit goes to a block's collator. 

This can be done in a separate pallet/the same one/Storage Provider Pallet/
A lot of room for maneuvers here.

**Comment by jmg-duarte** [comment]
Closing since we're not doing collators
